### ISSUE TITLE
jira::facts don't work with All-in-One Puppet 4.x agent

### ISSUE THREAD

**Issue by aharden** [voxpupuli/puppet-jira#151]
The AIO agent moved its ruby to /opt/puppetlabs/puppet/bin/ruby.  "PE" detection logic in jira::facts hasn't been adjusted for the AIO agent.  As a result, on nodes with the AIO agent, jira_facts.rb exists at both /etc/facter/facts.d/ and /etc/puppetlabs/facter/facts.d, and neither has a path to ruby that works, so both report Facter errors on agent runs.  I know that changing the shebang in jira_facts.rb to #!/opt/puppetlabs/puppet/bin/ruby fixes this.  I will try to put in a PR with updated logic for the AIO agent.

**Comment by bastelfreak** [comment]
thanks for reporting this. It would be very cool if you can spin up a PR. We should be able to review + merge  + publish a fixed version in a short timeframe.

**Comment by dpisano** [comment]
I think that I figured out the logic to detect the AIO agent. Don't know if it will work with the AIO agent for PE. I don't have a way to test it on other version of puppet to see if still works with them. I can summit a PR to have you take a look at it.

**Comment by ekohl** [comment]
Looks like this was fixed by now.

**Comment by dpisano** [comment]
This is still a problem unless you have ruby installed on your system. If you are using the OSS version of Puppet `facts.rb` will be made looking for the system installed ruby. As the AIO Puppet agent does not install ruby on the system, every time `facts.rb` is run it will fail because ruby is not installed. The only way around this is it installed ruby on the system or change `jira::facts` to check for the AIO agent and make `facts.rb` pointing to the puppet bundled ruby.

**Comment by ekohl** [comment]
Ah, so this is 
https://github.com/voxpupuli/puppet-jira/blob/0f32b04d9e32d7285290cdacd616daab73684f2c/manifests/facts.pp#L30-L38

I'd suggest changing the check to `fact('aio_agent_version') =~ String[1]`. Since I don't use it myself, I can't test it out but that should be a pretty trivial PR.

**Comment by dpisano** [comment]
Let me try to do it this weekend. I have a fork with this fixed for some time. I also have a dev environment to test it in.

**Comment by dpisano** [comment]
I have submitted the PR, but it looks like I need to update some of the tests too. I'm pretty sure that Puppet 5 and 6 only come in an AIO version. If that is the case in `jira_facts_spec.rb` should I just set `regexp_oss = %r{^#\!/opt/puppetlabs/puppet/bin/ruby$}`?

**Comment by ekohl** [comment]
I think so yes. Since Puppet 4, Puppetlabs only ships AIO packages.
